require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AllowedUsersController do

  # This should return the minimal set of attributes required to create a valid
  # AllowedUser. As you add validations to AllowedUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AllowedUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all allowed_users as @allowed_users" do
      allowed_user = AllowedUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:allowed_users).should eq([allowed_user])
    end
  end

  describe "GET show" do
    it "assigns the requested allowed_user as @allowed_user" do
      allowed_user = AllowedUser.create! valid_attributes
      get :show, {:id => allowed_user.to_param}, valid_session
      assigns(:allowed_user).should eq(allowed_user)
    end
  end

  describe "GET new" do
    it "assigns a new allowed_user as @allowed_user" do
      get :new, {}, valid_session
      assigns(:allowed_user).should be_a_new(AllowedUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested allowed_user as @allowed_user" do
      allowed_user = AllowedUser.create! valid_attributes
      get :edit, {:id => allowed_user.to_param}, valid_session
      assigns(:allowed_user).should eq(allowed_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AllowedUser" do
        expect {
          post :create, {:allowed_user => valid_attributes}, valid_session
        }.to change(AllowedUser, :count).by(1)
      end

      it "assigns a newly created allowed_user as @allowed_user" do
        post :create, {:allowed_user => valid_attributes}, valid_session
        assigns(:allowed_user).should be_a(AllowedUser)
        assigns(:allowed_user).should be_persisted
      end

      it "redirects to the created allowed_user" do
        post :create, {:allowed_user => valid_attributes}, valid_session
        response.should redirect_to(AllowedUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved allowed_user as @allowed_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        AllowedUser.any_instance.stub(:save).and_return(false)
        post :create, {:allowed_user => {}}, valid_session
        assigns(:allowed_user).should be_a_new(AllowedUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AllowedUser.any_instance.stub(:save).and_return(false)
        post :create, {:allowed_user => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested allowed_user" do
        allowed_user = AllowedUser.create! valid_attributes
        # Assuming there are no other allowed_users in the database, this
        # specifies that the AllowedUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AllowedUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => allowed_user.to_param, :allowed_user => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested allowed_user as @allowed_user" do
        allowed_user = AllowedUser.create! valid_attributes
        put :update, {:id => allowed_user.to_param, :allowed_user => valid_attributes}, valid_session
        assigns(:allowed_user).should eq(allowed_user)
      end

      it "redirects to the allowed_user" do
        allowed_user = AllowedUser.create! valid_attributes
        put :update, {:id => allowed_user.to_param, :allowed_user => valid_attributes}, valid_session
        response.should redirect_to(allowed_user)
      end
    end

    describe "with invalid params" do
      it "assigns the allowed_user as @allowed_user" do
        allowed_user = AllowedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AllowedUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => allowed_user.to_param, :allowed_user => {}}, valid_session
        assigns(:allowed_user).should eq(allowed_user)
      end

      it "re-renders the 'edit' template" do
        allowed_user = AllowedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AllowedUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => allowed_user.to_param, :allowed_user => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested allowed_user" do
      allowed_user = AllowedUser.create! valid_attributes
      expect {
        delete :destroy, {:id => allowed_user.to_param}, valid_session
      }.to change(AllowedUser, :count).by(-1)
    end

    it "redirects to the allowed_users list" do
      allowed_user = AllowedUser.create! valid_attributes
      delete :destroy, {:id => allowed_user.to_param}, valid_session
      response.should redirect_to(allowed_users_url)
    end
  end

end
